#!/bin/sh
set -e

# =============================================================================
# TYPO3 Docker Entrypoint
# Handles environment variable substitution, permissions, and initial setup
# =============================================================================

if command -v nginx > /dev/null 2>&1; then
    VARIANT="Nginx"
else
    VARIANT="FPM-only"
fi

echo "================================================"
echo " TYPO3 Official Docker Image"
echo " PHP $(php -r 'echo PHP_VERSION;') | ${VARIANT} | Debian"
echo "================================================"

# -----------------------------------------------------------------------------
# Substitute environment variables in PHP config
# -----------------------------------------------------------------------------
envsubst_php() {
    local file="$1"
    if [ -f "$file" ]; then
        sed -i \
            -e "s|\${PHP_MEMORY_LIMIT}|${PHP_MEMORY_LIMIT:-512M}|g" \
            -e "s|\${PHP_MAX_EXECUTION_TIME}|${PHP_MAX_EXECUTION_TIME:-240}|g" \
            -e "s|\${PHP_UPLOAD_MAX_FILESIZE}|${PHP_UPLOAD_MAX_FILESIZE:-32M}|g" \
            -e "s|\${PHP_POST_MAX_SIZE}|${PHP_POST_MAX_SIZE:-32M}|g" \
            -e "s|\${PHP_MAX_INPUT_VARS}|${PHP_MAX_INPUT_VARS:-1500}|g" \
            "$file"
    fi
}

envsubst_php "/etc/php/${PHP_VERSION}/fpm/conf.d/99-typo3.ini"
envsubst_php "/etc/php/${PHP_VERSION}/cli/conf.d/99-typo3.ini"

# -----------------------------------------------------------------------------
# Set TYPO3_CONTEXT in Nginx (only for nginx variant)
# -----------------------------------------------------------------------------
if [ -f /etc/nginx/conf.d/default.conf ]; then
    sed -i "s|\$TYPO3_CONTEXT|${TYPO3_CONTEXT:-Production}|g" /etc/nginx/conf.d/default.conf
fi

# -----------------------------------------------------------------------------
# Ensure directory permissions
# -----------------------------------------------------------------------------
for dir in /var/www/html/public /var/www/html/var /var/www/html/config; do
    if [ -d "$dir" ]; then
        chown -R typo3:typo3 "$dir"
    fi
done

# Ensure TYPO3 writable directories exist
for dir in var/cache var/log var/lock var/session public/fileadmin public/_assets; do
    mkdir -p "/var/www/html/$dir"
    chown -R typo3:typo3 "/var/www/html/$dir"
done

# -----------------------------------------------------------------------------
# Generate AdditionalConfiguration.php from environment variables
# (only if it does not already exist)
# -----------------------------------------------------------------------------
ADDITIONAL_CONFIG="/var/www/html/config/system/additional.php"
if [ ! -f "$ADDITIONAL_CONFIG" ] && [ -n "$TYPO3_DB_HOST" ]; then
    mkdir -p "$(dirname "$ADDITIONAL_CONFIG")"
    chown -R typo3:typo3 "$(dirname "$ADDITIONAL_CONFIG")"

    cat > "$ADDITIONAL_CONFIG" <<EOPHP
<?php
// Auto-generated by TYPO3 Docker entrypoint from environment variables
// Override by mounting your own config/system/additional.php

\$GLOBALS['TYPO3_CONF_VARS']['DB']['Connections']['Default'] = [
    'driver' => '${TYPO3_DB_DRIVER}',
    'host' => '${TYPO3_DB_HOST}',
    'port' => ${TYPO3_DB_PORT:-3306},
    'dbname' => '${TYPO3_DB_NAME}',
    'user' => '${TYPO3_DB_USERNAME}',
    'password' => '${TYPO3_DB_PASSWORD}',
    'charset' => 'utf8mb4',
    'defaultTableOptions' => [
        'charset' => 'utf8mb4',
        'collation' => 'utf8mb4_unicode_ci',
    ],
];

// Trust reverse proxy headers (common in containerized environments)
\$GLOBALS['TYPO3_CONF_VARS']['SYS']['reverseProxyIP'] = '*';
\$GLOBALS['TYPO3_CONF_VARS']['SYS']['reverseProxyHeaderMultiValue'] = 'first';
\$GLOBALS['TYPO3_CONF_VARS']['SYS']['trustedHostsPattern'] = '.*';

// Logging to stdout/stderr (container best practice)
\$GLOBALS['TYPO3_CONF_VARS']['LOG']['writerConfiguration'] = [
    \TYPO3\CMS\Core\Log\LogLevel::WARNING => [
        \TYPO3\CMS\Core\Log\Writer\PhpErrorLogWriter::class => [],
    ],
];

// Redis cache backend (if REDIS_HOST is set)
if (getenv('REDIS_HOST')) {
    \$redisHost = getenv('REDIS_HOST');
    \$redisPort = getenv('REDIS_PORT') ?: 6379;

    \$GLOBALS['TYPO3_CONF_VARS']['SYS']['caching']['cacheConfigurations']['hash'] = [
        'backend' => \TYPO3\CMS\Core\Cache\Backend\RedisBackend::class,
        'options' => ['hostname' => \$redisHost, 'port' => \$redisPort, 'database' => 0],
    ];
    \$GLOBALS['TYPO3_CONF_VARS']['SYS']['caching']['cacheConfigurations']['pages'] = [
        'backend' => \TYPO3\CMS\Core\Cache\Backend\RedisBackend::class,
        'options' => ['hostname' => \$redisHost, 'port' => \$redisPort, 'database' => 1],
    ];
    \$GLOBALS['TYPO3_CONF_VARS']['SYS']['caching']['cacheConfigurations']['rootline'] = [
        'backend' => \TYPO3\CMS\Core\Cache\Backend\RedisBackend::class,
        'options' => ['hostname' => \$redisHost, 'port' => \$redisPort, 'database' => 2],
    ];
}

// SMTP mail transport (if SMTP_HOST is set)
if (getenv('SMTP_HOST')) {
    \$GLOBALS['TYPO3_CONF_VARS']['MAIL']['transport'] = 'smtp';
    \$GLOBALS['TYPO3_CONF_VARS']['MAIL']['transport_smtp_server'] = getenv('SMTP_HOST') . ':' . (getenv('SMTP_PORT') ?: '587');
    if (getenv('SMTP_USERNAME')) {
        \$GLOBALS['TYPO3_CONF_VARS']['MAIL']['transport_smtp_username'] = getenv('SMTP_USERNAME');
        \$GLOBALS['TYPO3_CONF_VARS']['MAIL']['transport_smtp_password'] = getenv('SMTP_PASSWORD');
    }
}
EOPHP

    chown typo3:typo3 "$ADDITIONAL_CONFIG"
    echo "[entrypoint] Generated additional.php from environment variables"
fi

# -----------------------------------------------------------------------------
# Run TYPO3 setup if requested
# -----------------------------------------------------------------------------
if [ "$1" = "typo3-setup" ]; then
    echo "[entrypoint] Running TYPO3 setup..."
    su -s /bin/sh typo3 -c "cd /var/www/html && vendor/bin/typo3 setup \
        --driver=${TYPO3_DB_DRIVER} \
        --host=${TYPO3_DB_HOST} \
        --port=${TYPO3_DB_PORT:-3306} \
        --dbname=${TYPO3_DB_NAME} \
        --username=${TYPO3_DB_USERNAME} \
        --password=${TYPO3_DB_PASSWORD} \
        --admin-username=${TYPO3_SETUP_ADMIN_USERNAME:-admin} \
        --admin-user-password=${TYPO3_SETUP_ADMIN_PASSWORD} \
        --admin-email=${TYPO3_SETUP_ADMIN_EMAIL:-admin@example.com} \
        --no-interaction"
    echo "[entrypoint] TYPO3 setup complete"
    shift
fi

# -----------------------------------------------------------------------------
# Execute command
# -----------------------------------------------------------------------------
exec "$@"
